//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMigracion.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTO
    {
        public int Id { get; set; }
        public string TipoDocumento { get; set; }
        public string NumeroDocumento { get; set; }
        public System.DateTime FechaExpiracion { get; set; }
        public int IdViajero { get; set; }
    
        public virtual VIAJERO VIAJERO { get; set; }
    }
}
