//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMigracion.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMIENTO
    {
        public int Id { get; set; }
        public int IdViajero { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Destino { get; set; }
        public int Origen { get; set; }
        public string TipoSolicitud { get; set; }
        public int IdUsuario { get; set; }
    
        public virtual PAIS PAIS { get; set; }
        public virtual PAIS PAIS1 { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual VIAJERO VIAJERO { get; set; }
    }
}
